/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/life-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Life Path number - Most important numerology calculation
         * @description Calculate your Life Path number from your birth date using Pythagorean numerology. This is the most significant number in your numerology chart, revealing your life purpose, natural talents, and destiny path. Automatically detects Master Numbers (11, 22, 33) and Karmic Debt numbers (13, 14, 16, 19). Returns comprehensive interpretation including personality traits, strengths, challenges, career guidance, relationship compatibility, and spiritual insights. Perfect for numerology apps, birth chart calculators, life purpose discovery tools, personal development platforms, and astrology services. Get detailed 300-500 word meanings for all numbers 1-9, 11, 22, and 33.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Birth year (1900-2100)
                         * @example 1990
                         */
                        year: number;
                        /**
                         * @description Birth month (1-12)
                         * @example 7
                         */
                        month: number;
                        /**
                         * @description Birth day (1-31)
                         * @example 15
                         */
                        day: number;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Life Path number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Life Path number (1-9, 11, 22, 33)
                             * @example 5
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation breakdown
                             * @example 1990 + 7 + 15 = 2012 → 2+0+1+2 = 5
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether this number has karmic debt (13, 14, 16, 19)
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if present (13, 14, 16, 19)
                             * @example 14
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Archetype title
                                 * @example The Freedom Seeker
                                 */
                                title: string;
                                /**
                                 * @description Key personality traits
                                 * @example [
                                 *       "adventurous",
                                 *       "freedom",
                                 *       "versatile",
                                 *       "dynamic",
                                 *       "curious"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description
                                 * @example People with a 5 Life Path number are on a lifelong adventure. They are ready for anything and want to soak up every experience this world has to offer...
                                 */
                                description: string;
                                /**
                                 * @description Core strengths and positive qualities
                                 * @example [
                                 *       "Adaptability",
                                 *       "Communication",
                                 *       "Curiosity",
                                 *       "Resourcefulness"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Common challenges and lessons to overcome
                                 * @example [
                                 *       "Restlessness",
                                 *       "Commitment issues",
                                 *       "Impulsiveness"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career guidance and professional strengths
                                 * @example Suited for careers that offer variety and freedom: travel, sales, marketing, journalism, entrepreneurship...
                                 */
                                career: string;
                                /**
                                 * @description Relationship dynamics and compatibility insights
                                 * @example In relationships, needs freedom and variety. Makes exciting partner but may struggle with long-term commitment...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual path and higher purpose guidance
                                 * @example Spiritual growth comes through diverse experiences. Learns life lessons by exploring different philosophies and cultures...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Expression number - Natural talents and life goals
         * @description Calculate your Expression (Destiny) number from your full birth name using Pythagorean numerology. This number reveals your natural talents, abilities, and life goals. It shows what you came here to do and what tools you have to accomplish your life purpose. Returns comprehensive interpretation including personality traits, career paths, relationship dynamics, and spiritual insights. Automatically detects Master Numbers (11, 22, 33). Perfect for name numerology apps, career guidance tools, personal development platforms, and talent assessment services. Get detailed 300-500 word meanings for all numbers 1-9, 11, 22, and 33.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Full birth name (first, middle, last)
                         * @example John William Smith
                         */
                        fullName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Expression number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Expression number (1-9, 11, 22, 33)
                             * @example 7
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation breakdown showing all name values
                             * @example 1+6+8+5 + 5+9+3+3+9+1+4 + 1+4+9+2+8 = 78 → 7+8 = 15 → 1+5 = 6
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether calculation passed through karmic debt number
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if detected (13, 14, 16, 19)
                             * @example 14
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Archetype title
                                 * @example The Seeker
                                 */
                                title: string;
                                /**
                                 * @description Key personality traits
                                 * @example [
                                 *       "analytical",
                                 *       "spiritual",
                                 *       "wise",
                                 *       "introspective",
                                 *       "perfectionist"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description
                                 * @example People with a 7 Expression number have a natural gift for analysis and investigation...
                                 */
                                description: string;
                                /**
                                 * @description Core strengths and talents
                                 * @example [
                                 *       "Deep thinking",
                                 *       "Intuition",
                                 *       "Research ability",
                                 *       "Spiritual insight"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Common challenges to overcome
                                 * @example [
                                 *       "Aloofness",
                                 *       "Over-analysis",
                                 *       "Skepticism"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career guidance based on natural talents
                                 * @example Suited for research, science, spirituality, teaching, technology...
                                 */
                                career: string;
                                /**
                                 * @description Relationship dynamics and compatibility
                                 * @example Needs intellectual connection and personal space in relationships...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual path and higher purpose
                                 * @example Natural spiritual seeker with deep connection to inner wisdom...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/soul-urge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Soul Urge number - Inner motivations and desires
         * @description Calculate your Soul Urge (Heart Desire) number from the vowels in your birth name using Pythagorean numerology. This number reveals your innermost desires, motivations, and what your soul truly wants to experience. It shows what drives you from within, your emotional needs, and what brings you fulfillment. Returns comprehensive interpretation including personality traits, emotional needs, relationship desires, and spiritual longings. Automatically detects Master Numbers (11, 22, 33). Perfect for self-discovery apps, emotional intelligence tools, relationship counseling platforms, and personal development services. Get detailed 300-500 word meanings for all numbers 1-9, 11, 22, and 33.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Full birth name (vowels will be extracted)
                         * @example John William Smith
                         */
                        fullName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Soul Urge number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Soul Urge number (1-9, 11, 22, 33)
                             * @example 6
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation showing vowel values only
                             * @example 6+9+1 + 9+9+1 + 9 = 44 → 4+4 = 8
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether calculation passed through karmic debt number
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if detected (13, 14, 16, 19)
                             * @example 13
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Archetype title
                                 * @example The Nurturer
                                 */
                                title: string;
                                /**
                                 * @description Key inner traits and motivations
                                 * @example [
                                 *       "caring",
                                 *       "responsible",
                                 *       "harmonious",
                                 *       "protective",
                                 *       "service"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description of inner nature
                                 * @example People with a 6 Soul Urge number have a deep desire to nurture and care for others...
                                 */
                                description: string;
                                /**
                                 * @description Core emotional strengths
                                 * @example [
                                 *       "Compassion",
                                 *       "Responsibility",
                                 *       "Harmony creation",
                                 *       "Service orientation"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Inner challenges to balance
                                 * @example [
                                 *       "Over-responsibility",
                                 *       "Martyrdom",
                                 *       "Interference"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career paths that satisfy inner needs
                                 * @example Emotionally fulfilling in healing, counseling, teaching, caregiving...
                                 */
                                career: string;
                                /**
                                 * @description Relationship needs and emotional dynamics
                                 * @example Seeks to create harmony and provide emotional support in relationships...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual desires and inner path
                                 * @example Spiritual fulfillment through service and unconditional love...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Personality number - How others perceive you
         * @description Calculate your Personality number from the consonants in your birth name using Pythagorean numerology. This number reveals how others perceive you, your outer personality, and first impressions you make. It represents the mask you show the world and your social persona. Returns comprehensive interpretation including public image, social dynamics, professional presence, and relationship first impressions. Automatically detects Master Numbers (11, 22, 33). Perfect for personal branding apps, social skills training, professional development platforms, and communication coaching services. Get detailed 300-500 word meanings for all numbers 1-9, 11, 22, and 33.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Full birth name (consonants will be extracted)
                         * @example John William Smith
                         */
                        fullName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Personality number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Personality number (1-9, 11, 22, 33)
                             * @example 9
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation showing consonant values only
                             * @example 1+8+5 + 5+3+3+4 + 1+4+2+8 = 44 → 4+4 = 8
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether calculation passed through karmic debt number
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if detected (13, 14, 16, 19)
                             * @example 16
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Public archetype
                                 * @example The Humanitarian
                                 */
                                title: string;
                                /**
                                 * @description Key outer personality traits
                                 * @example [
                                 *       "compassionate",
                                 *       "charismatic",
                                 *       "idealistic",
                                 *       "generous",
                                 *       "wise"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description of public persona
                                 * @example People with a 9 Personality number project warmth and compassion to others...
                                 */
                                description: string;
                                /**
                                 * @description Core outer strengths
                                 * @example [
                                 *       "Charisma",
                                 *       "Compassion",
                                 *       "Wisdom",
                                 *       "Universal understanding"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Outer personality challenges
                                 * @example [
                                 *       "Emotional distance",
                                 *       "Impracticality",
                                 *       "Scattered energy"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Professional presence and career guidance
                                 * @example Public image suited for humanitarian work, counseling, arts, teaching...
                                 */
                                career: string;
                                /**
                                 * @description Relationship first impressions and social dynamics
                                 * @example First impression is warm and accepting, attracts many connections...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual presence and public path
                                 * @example Projects spiritual wisdom and universal love to the world...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/birth-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Birth Day number - Special talents from day of birth
         * @description Calculate your Birth Day number from the day you were born (1-31) using Pythagorean numerology. This number reveals special talents and abilities you possess from birth. It shows natural gifts that can help you achieve your life purpose. Returns comprehensive interpretation including innate talents, natural abilities, career advantages, and how to leverage your special gifts. Automatically detects Master Numbers (11, 22) and reduces double-digit days. Perfect for talent discovery apps, career counseling platforms, personal development services, and skill assessment tools. Get detailed 300-500 word meanings for all numbers 1-9, 11, and 22.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Day of birth (1-31)
                         * @example 23
                         */
                        day: number;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Birth Day number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Birth Day number (1-9, 11, 22)
                             * @example 5
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation (single digit if 1-9)
                             * @example 23 → 2+3 = 5
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether day number has karmic debt
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if present (13, 14, 16, 19)
                             * @example 19
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Talent archetype
                                 * @example The Freedom Seeker
                                 */
                                title: string;
                                /**
                                 * @description Key innate talents
                                 * @example [
                                 *       "versatile",
                                 *       "adaptable",
                                 *       "communicative",
                                 *       "adventurous",
                                 *       "dynamic"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description of special gifts
                                 * @example People born on a 5 Birth Day have natural versatility and adaptability...
                                 */
                                description: string;
                                /**
                                 * @description Core innate strengths
                                 * @example [
                                 *       "Adaptability",
                                 *       "Communication",
                                 *       "Quick learning",
                                 *       "Versatility"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Natural challenges to balance
                                 * @example [
                                 *       "Restlessness",
                                 *       "Scattered energy",
                                 *       "Commitment avoidance"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career paths that leverage natural abilities
                                 * @example Natural talents for travel, sales, communication, entrepreneurship...
                                 */
                                career: string;
                                /**
                                 * @description Relationship dynamics based on innate nature
                                 * @example Brings excitement and variety to relationships, needs freedom...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual path and natural gifts application
                                 * @example Spiritual growth through diverse experiences and freedom...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maturity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Maturity number - Who you become in later life
         * @description Calculate your Maturity (Realization) number by adding Life Path and Expression numbers using Pythagorean numerology. This number reveals who you become in the second half of life, typically manifesting after age 35-40. It shows the ultimate goal of personal development and mature self-expression. Returns comprehensive interpretation including life transformation, mature personality, later-life purpose, and wisdom development. Automatically detects Master Numbers (11, 22, 33). Perfect for life coaching apps, midlife guidance platforms, personal development services, and aging wisdom tools. Get detailed 300-500 word meanings for all numbers 1-9, 11, 22, and 33.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Your Life Path number (1-9, 11, 22, 33)
                         * @example 5
                         */
                        lifePath: number;
                        /**
                         * @description Your Expression number (1-9, 11, 22, 33)
                         * @example 7
                         */
                        expression: number;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Maturity number with detailed interpretation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Maturity number (1-9, 11, 22, 33)
                             * @example 3
                             */
                            number: number;
                            /**
                             * @description Step-by-step calculation showing Life Path + Expression
                             * @example 5 + 7 = 12 → 1+2 = 3
                             */
                            calculation: string;
                            /**
                             * @description Number type classification
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            /**
                             * @description Whether calculation passed through karmic debt number
                             * @example false
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description Karmic debt number if detected (13, 14, 16, 19)
                             * @example 14
                             */
                            karmicDebtNumber?: number;
                            meaning: {
                                /**
                                 * @description Mature archetype
                                 * @example The Creative Communicator
                                 */
                                title: string;
                                /**
                                 * @description Key mature personality traits
                                 * @example [
                                 *       "expressive",
                                 *       "creative",
                                 *       "joyful",
                                 *       "communicative",
                                 *       "optimistic"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description of mature self
                                 * @example People with a 3 Maturity number grow into creative and joyful expression...
                                 */
                                description: string;
                                /**
                                 * @description Core mature strengths
                                 * @example [
                                 *       "Creative expression",
                                 *       "Communication",
                                 *       "Joy",
                                 *       "Social charm"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Mature challenges to balance
                                 * @example [
                                 *       "Scattered energy",
                                 *       "Superficiality",
                                 *       "Over-sensitivity"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career paths for mature stage
                                 * @example Later-life fulfillment in creative fields, communication, arts, entertainment...
                                 */
                                career: string;
                                /**
                                 * @description Relationship dynamics in later life
                                 * @example Mature relationships become more expressive and joyful...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual path in later life
                                 * @example Spiritual maturity through creative expression and joy...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/karmic-lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Karmic Lessons - Life lessons from missing numbers
         * @description Analyze your Karmic Lessons from your birth name using Pythagorean numerology. Karmic lessons are indicated by numbers missing from your name (numbers 1-9 that do not appear). These represent challenges you came to learn and skills you need to develop in this lifetime. Returns comprehensive analysis including missing numbers, specific lessons for each, challenges to overcome, and practical guidance for development. Perfect for spiritual growth apps, personal development platforms, life coaching services, and self-improvement tools. Get detailed lesson descriptions, development strategies, and practical exercises for each missing number.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Full birth name to analyze for missing numbers
                         * @example John William Smith
                         */
                        fullName: string;
                    };
                };
            };
            responses: {
                /** @description Successfully analyzed karmic lessons with development guidance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Numbers missing from name (karmic lessons)
                             * @example [
                             *       2,
                             *       4,
                             *       8
                             *     ]
                             */
                            missingNumbers: number[];
                            lessons: {
                                /**
                                 * @description Missing number
                                 * @example 2
                                 */
                                number: number;
                                /**
                                 * @description Core lesson summary
                                 * @example Learn cooperation, patience, and sensitivity
                                 */
                                lesson: string;
                                /**
                                 * @description Detailed lesson explanation
                                 * @example Missing number 2 indicates challenges with teamwork and relationships...
                                 */
                                description: string;
                                /**
                                 * @description Practical guidance for developing this quality
                                 * @example Practice active listening, work on group projects, develop empathy...
                                 */
                                howToOvercome: string;
                            }[];
                            /**
                             * @description Count of each number present in name
                             * @example {
                             *       "1": 3,
                             *       "3": 2,
                             *       "5": 4,
                             *       "6": 1,
                             *       "7": 2,
                             *       "9": 2
                             *     }
                             */
                            presentNumbers: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/karmic-debt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Karmic Debt numbers - Past life challenges (13, 14, 16, 19)
         * @description Check for Karmic Debt numbers (13, 14, 16, 19) in Life Path, Expression, Soul Urge, or Personality calculations using Pythagorean numerology. Karmic debt indicates challenges carried from past lives that must be resolved in this lifetime. These numbers appear during reduction and represent specific lessons and tests. Returns comprehensive analysis including debt descriptions, challenges to overcome, and resolution guidance. Perfect for spiritual growth apps, karmic astrology platforms, past life exploration services, and personal transformation tools. Get detailed meanings for all four karmic debt numbers with practical resolution strategies.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Birth year (checks Life Path)
                         * @example 1990
                         */
                        year?: number;
                        /**
                         * @description Birth month (checks Life Path)
                         * @example 7
                         */
                        month?: number;
                        /**
                         * @description Birth day (checks Life Path)
                         * @example 15
                         */
                        day?: number;
                        /**
                         * @description Full birth name (checks Expression, Soul Urge, Personality)
                         * @example John William Smith
                         */
                        fullName?: string;
                    };
                };
            };
            responses: {
                /** @description Successfully detected karmic debt with detailed meanings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Whether any karmic debt numbers were detected
                             * @example true
                             */
                            hasKarmicDebt: boolean;
                            /**
                             * @description All karmic debt numbers found (13, 14, 16, 19)
                             * @example [
                             *       14,
                             *       16
                             *     ]
                             */
                            debtNumbers: number[];
                            meanings: {
                                /**
                                 * @description Karmic debt number
                                 * @example 14
                                 */
                                number: number;
                                /**
                                 * @description Debt title and nature
                                 * @example Karmic Debt of Abuse of Freedom
                                 */
                                description: string;
                                /**
                                 * @description Detailed explanation of past life issue and current challenges
                                 * @example Past life misuse of personal freedom through excess or manipulation...
                                 */
                                challenge: string;
                                /**
                                 * @description Guidance for resolving karmic debt in this lifetime
                                 * @example Learn balance, moderation, and responsible use of freedom...
                                 */
                                resolution: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personal-year": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Personal Year - Annual cycle and forecast for current year
         * @description Calculate your Personal Year number from your birth month, day, and current year using Pythagorean numerology. Personal Year runs in 9-year cycles (1-9) and reveals the theme, opportunities, and challenges for the current year. Each year has a specific energy and lessons. Returns comprehensive annual forecast including year theme, opportunities, challenges, and actionable advice. Perfect for yearly planning apps, life coaching platforms, astrology services, and personal development tools. Get detailed forecasts for all 9 Personal Year cycles with practical guidance.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Birth month (1-12)
                         * @example 7
                         */
                        month: number;
                        /**
                         * @description Birth day (1-31)
                         * @example 15
                         */
                        day: number;
                        /**
                         * @description Year to calculate (defaults to current year)
                         * @example 2025
                         */
                        year?: number;
                    };
                };
            };
            responses: {
                /** @description Successfully calculated Personal Year with forecast */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Personal Year number (1-9)
                             * @example 5
                             */
                            personalYear: number;
                            /**
                             * @description Position in the 9-year cycle
                             * @example Year 5 of 9
                             */
                            cycle: string;
                            /**
                             * @description Main theme of the year
                             * @example Freedom and Change
                             */
                            theme: string;
                            /**
                             * @description Detailed year forecast (200-300 words)
                             * @example This is a year of freedom, change, and unexpected opportunities. You will feel restless and eager for new experiences...
                             */
                            forecast: string;
                            /**
                             * @description Key opportunities in this year
                             * @example [
                             *       "Travel and adventure",
                             *       "Career changes",
                             *       "New connections",
                             *       "Learning"
                             *     ]
                             */
                            opportunities: string[];
                            /**
                             * @description Challenges to navigate
                             * @example [
                             *       "Restlessness",
                             *       "Scattered energy",
                             *       "Impulsive decisions"
                             *     ]
                             */
                            challenges: string[];
                            /**
                             * @description Practical guidance for navigating the year
                             * @example Embrace change and new experiences but maintain some stability. Stay flexible and open-minded...
                             */
                            advice: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Compatibility - Relationship dynamics between two people
         * @description Calculate numerology compatibility between two people using their Life Path, Expression, and Soul Urge numbers based on Pythagorean numerology. Provides comprehensive relationship analysis with overall compatibility score (0-100), individual aspect compatibility (Life Path 50% weight, Expression 30%, Soul Urge 20%), relationship strengths, challenges, and practical advice. Uses detailed compatibility matrix for all number combinations. Perfect for dating apps, relationship counseling platforms, matchmaking services, and compatibility tools. Get actionable insights for improving relationship dynamics.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        person1: {
                            /**
                             * @description Person 1 Life Path number (1-9, 11, 22, 33)
                             * @example 5
                             */
                            lifePath: number;
                            /**
                             * @description Person 1 Expression number (1-9, 11, 22, 33)
                             * @example 7
                             */
                            expression: number;
                            /**
                             * @description Person 1 Soul Urge number (1-9, 11, 22, 33)
                             * @example 6
                             */
                            soulUrge: number;
                        };
                        person2: {
                            /**
                             * @description Person 2 Life Path number (1-9, 11, 22, 33)
                             * @example 3
                             */
                            lifePath: number;
                            /**
                             * @description Person 2 Expression number (1-9, 11, 22, 33)
                             * @example 9
                             */
                            expression: number;
                            /**
                             * @description Person 2 Soul Urge number (1-9, 11, 22, 33)
                             * @example 2
                             */
                            soulUrge: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Successfully calculated compatibility with detailed analysis */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Overall compatibility score (0-100)
                             * @example 78
                             */
                            overallScore: number;
                            /**
                             * @description Compatibility rating (Poor/Fair/Good/Excellent/Exceptional)
                             * @example Good
                             */
                            rating: string;
                            lifePath: {
                                /**
                                 * @description Person 1 Life Path number
                                 * @example 5
                                 */
                                person1: number;
                                /**
                                 * @description Person 2 Life Path number
                                 * @example 3
                                 */
                                person2: number;
                                /**
                                 * @description Life Path compatibility score (0-100)
                                 * @example 85
                                 */
                                compatibility: number;
                                /**
                                 * @description Detailed Life Path compatibility analysis
                                 * @example 5 and 3 create an exciting dynamic partnership...
                                 */
                                description: string;
                            };
                            expression: {
                                /**
                                 * @description Person 1 Expression number
                                 * @example 7
                                 */
                                person1: number;
                                /**
                                 * @description Person 2 Expression number
                                 * @example 9
                                 */
                                person2: number;
                                /**
                                 * @description Expression compatibility score (0-100)
                                 * @example 70
                                 */
                                compatibility: number;
                                /**
                                 * @description Detailed Expression compatibility analysis
                                 * @example 7 and 9 share spiritual depth...
                                 */
                                description: string;
                            };
                            soulUrge: {
                                /**
                                 * @description Person 1 Soul Urge number
                                 * @example 6
                                 */
                                person1: number;
                                /**
                                 * @description Person 2 Soul Urge number
                                 * @example 2
                                 */
                                person2: number;
                                /**
                                 * @description Soul Urge compatibility score (0-100)
                                 * @example 90
                                 */
                                compatibility: number;
                                /**
                                 * @description Detailed Soul Urge compatibility analysis
                                 * @example 6 and 2 have complementary emotional needs...
                                 */
                                description: string;
                            };
                            /**
                             * @description Key relationship strengths
                             * @example [
                             *       "Complementary personalities",
                             *       "Shared values",
                             *       "Mutual growth support",
                             *       "Emotional harmony"
                             *     ]
                             */
                            strengths: string[];
                            /**
                             * @description Potential relationship challenges
                             * @example [
                             *       "Different communication styles",
                             *       "Need for independence vs togetherness",
                             *       "Pace of life differences"
                             *     ]
                             */
                            challenges: string[];
                            /**
                             * @description Practical relationship advice
                             * @example This relationship thrives on mutual respect and space for individual growth. Focus on...
                             */
                            advice: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Complete Numerology Chart - Full profile analysis
         * @description Generate a comprehensive numerology chart combining all major calculations: Life Path, Expression, Soul Urge, Personality, Birth Day, Maturity, Karmic Lessons, Karmic Debt, and Personal Year. This single endpoint provides everything needed for a full numerology reading. Returns detailed interpretations for all numbers, karmic analysis, yearly forecast, and holistic summary. Perfect for numerology apps, complete reading services, birth chart generators, and comprehensive analysis tools. Save multiple API calls by getting the full chart in one request. Ideal for generating PDF reports or detailed user profiles.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Full birth name
                         * @example John William Smith
                         */
                        fullName: string;
                        /**
                         * @description Birth year (1900-2100)
                         * @example 1990
                         */
                        year: number;
                        /**
                         * @description Birth month (1-12)
                         * @example 7
                         */
                        month: number;
                        /**
                         * @description Birth day (1-31)
                         * @example 15
                         */
                        day: number;
                        /**
                         * @description Year for Personal Year calculation (defaults to current year)
                         * @example 2025
                         */
                        currentYear?: number;
                    };
                };
            };
            responses: {
                /** @description Successfully generated complete numerology chart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profile: {
                                /** @example John William Smith */
                                name: string;
                                /** @example 1990-07-15 */
                                birthdate: string;
                            };
                            coreNumbers: {
                                lifePath: {
                                    number: number;
                                    calculation: string;
                                    /** @enum {string} */
                                    type: "single" | "master";
                                    hasKarmicDebt: boolean;
                                    karmicDebtNumber?: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                                expression: {
                                    number: number;
                                    calculation: string;
                                    /** @enum {string} */
                                    type: "single" | "master";
                                    hasKarmicDebt: boolean;
                                    karmicDebtNumber?: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                                soulUrge: {
                                    number: number;
                                    calculation: string;
                                    /** @enum {string} */
                                    type: "single" | "master";
                                    hasKarmicDebt: boolean;
                                    karmicDebtNumber?: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                                personality: {
                                    number: number;
                                    calculation: string;
                                    /** @enum {string} */
                                    type: "single" | "master";
                                    hasKarmicDebt: boolean;
                                    karmicDebtNumber?: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                                birthDay: {
                                    number: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                                maturity: {
                                    number: number;
                                    calculation: string;
                                    /** @enum {string} */
                                    type: "single" | "master";
                                    hasKarmicDebt: boolean;
                                    karmicDebtNumber?: number;
                                    meaning: {
                                        title: string;
                                        keywords: string[];
                                        description: string;
                                        strengths: string[];
                                        challenges: string[];
                                        career: string;
                                        relationships: string;
                                        spirituality: string;
                                    };
                                };
                            };
                            additionalInsights: {
                                karmicLessons: {
                                    missingNumbers: number[];
                                    lessons: {
                                        number: number;
                                        lesson: string;
                                        description: string;
                                        howToOvercome: string;
                                    }[];
                                    presentNumbers: {
                                        [key: string]: number;
                                    };
                                };
                                karmicDebt: {
                                    hasKarmicDebt: boolean;
                                    debtNumbers: number[];
                                    meanings: {
                                        number: number;
                                        description: string;
                                        challenge: string;
                                        resolution: string;
                                    }[];
                                };
                                personalYear: {
                                    personalYear: number;
                                    cycle: string;
                                    theme: string;
                                    forecast: string;
                                    opportunities: string[];
                                    challenges: string[];
                                    advice: string;
                                };
                            };
                            /**
                             * @description Holistic summary of the complete chart
                             * @example Your numerology chart reveals a Life Path 5 personality seeking freedom and adventure...
                             */
                            summary: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meanings/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Number Meaning - Interpretation for any number 1-9, 11, 22, 33
         * @description Get the complete meaning and interpretation for any numerology number (1-9, 11, 22, 33) using Pythagorean numerology. Returns comprehensive description including archetype title, keywords, personality traits, strengths, weaknesses, career guidance, relationship dynamics, and spiritual insights. Master numbers (11, 22, 33) include amplified meanings with their reduced base number. Perfect for numerology reference tools, educational apps, quick lookups, and building custom numerology calculators. Get detailed 300-500 word meanings from authoritative source (Hans Decoz - 50+ years experience).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numerology number (1-9, 11, 22, 33) */
                    number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved number meaning */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Requested number
                             * @example 5
                             */
                            number: number;
                            /**
                             * @description Number type
                             * @example single
                             * @enum {string}
                             */
                            type: "single" | "master";
                            meaning: {
                                /**
                                 * @description Archetype title
                                 * @example The Freedom Seeker
                                 */
                                title: string;
                                /**
                                 * @description Key personality traits and qualities
                                 * @example [
                                 *       "freedom",
                                 *       "adventure",
                                 *       "versatile",
                                 *       "dynamic",
                                 *       "curious"
                                 *     ]
                                 */
                                keywords: string[];
                                /**
                                 * @description Comprehensive 300-500 word description
                                 * @example People with a 5 energy are on a lifelong adventure seeking freedom and variety...
                                 */
                                description: string;
                                /**
                                 * @description Core strengths and positive qualities
                                 * @example [
                                 *       "Adaptability",
                                 *       "Communication",
                                 *       "Curiosity",
                                 *       "Resourcefulness"
                                 *     ]
                                 */
                                strengths: string[];
                                /**
                                 * @description Common challenges and growth areas
                                 * @example [
                                 *       "Restlessness",
                                 *       "Commitment issues",
                                 *       "Impulsiveness"
                                 *     ]
                                 */
                                challenges: string[];
                                /**
                                 * @description Career guidance and professional strengths
                                 * @example Suited for careers offering variety and freedom: travel, sales, marketing, journalism...
                                 */
                                career: string;
                                /**
                                 * @description Relationship dynamics and compatibility insights
                                 * @example Needs freedom and variety in relationships, makes exciting partner...
                                 */
                                relationships: string;
                                /**
                                 * @description Spiritual path and higher purpose guidance
                                 * @example Spiritual growth through diverse experiences and exploring different philosophies...
                                 */
                                spirituality: string;
                            };
                        };
                    };
                };
                /** @description Invalid number (must be 1-9, 11, 22, or 33) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Number meaning not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
